# Generated by Django 4.2.7 on 2023-11-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
